apiVersion: apps/v1 # This is a deployment (apps/v1 API)
kind: Deployment
metadata:
  name: restaurant-management-service
  labels:
    app: restaurant-management-service
spec:
  replicas: 2 # Runs 2 copies ( reliability & load balancing)
  selector:
    matchLabels:
      app: restaurant-management-service
  template:
    metadata:
      labels:
        app: restaurant-management-service
    spec:
      containers:
        - name: restaurant-management-service
          image: tinykav/restaurant-service:latest # Uses our Docker image from Docker Hub
          imagePullPolicy: Always # Always pull the newest image
          ports:
            - containerPort: 5000 # App listens on port 5000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_URI # Pulls MongoDB URI from secret
            - name: DEBUG
              value: "true" # Enables debug mode for logs
