apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-management-service
  labels:
    app: restaurant-management-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-management-service
  template:
    metadata:
      labels:
        app: restaurant-management-service
    spec:
      containers:
        - name: restaurant-management-service
          image: malindid/restaurant-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_URI
            - name: DEBUG
              value: "true"
