apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
type: Opaque
stringData:
  MONGO_URI: mongodb+srv://y3s2projectgroup:JuQT6yqnVdZ6FQ97@foodflix.j0p0p.mongodb.net/
  jwt-secret: jwt_secret_key
