# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: malindid/order-service:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: db-uri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
            - name: RESTAURANT_SERVICE_URL
              value: "http://restaurant-service:5001"
            - name: DELIVERY_SERVICE_URL
              value: "http://delivery-service:5003"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification-service:5004"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:3000"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq-service:5672"
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
