# apiVersion: v1

# backend/notification-service/k8s/notification-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
type: Opaque
stringData:
  MONGO_URI: mongodb+srv://y3s2projectgroup:JuQT6yqnVdZ6FQ97@foodflix.j0p0p.mongodb.net/foodflix-notifications?retryWrites=true&w=majority
  JWT_SECRET: jwt_secret_key
  SENDGRID_API_KEY: SG.xxxxxx
  TWILIO_ACCOUNT_SID: ACxxxxxxxxxxxxxxxxxxxx
  TWILIO_AUTH_TOKEN: your_twilio_auth_token
  TWILIO_PHONE_NUMBER: "+1234567890"
