apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
type: Opaque
data:
  DB_URI: mongodb+srv://y3s2projectgroup:JuQT6yqnVdZ6FQ97@foodflix.j0p0p.mongodb.net/ 
  SENDGRID_API_KEY: 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
  JWT_SECRET: jwt_secret_key
