apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  type: NodePort
  ports:
    - port: 5004
      targetPort: 5004
      nodePort: 30001
