apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
type: Opaque
data:
  # These values should be base64 encoded in a real deployment
  # Sample values for demonstration purposes
  stripe-secret-key: YzJ0ZmRHVnpkRjgxTVhsdmRYSmZhMlY1WDJobGNtVT0=
  stripe-webhook-secret: ZDJoelpXTmZlVzkxY2w5emRISnBjR1ZmZDJWaWFHOXZhMTl6WldOeVpYUT0=
  