apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: malindid/payment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3002"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: jwt-secret
            - name: JWT_EXPIRE
              value: "30d"
            - name: ORDER_SERVICE_URL
              value: "http://order-service:4000"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification-service:5004"
            - name: CLIENT_URL
              value: "http://frontend:3001"
            - name: DELIVERY_SERVICE_URL
              value: "http://delivery-service:5003"
            - name: CORS_ALLOW_ORIGIN
              value: "*"
            # Stripe configuration
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: stripe-secret-key
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: stripe-webhook-secret
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /api/payments/health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/payments/health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
