apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
type: Opaque
stringData:
  MONGO_URI: mongodb+srv://y3s2projectgroup:JuQT6yqnVdZ6FQ97@foodflix.j0p0p.mongodb.net/
  stripe-secret-key: sk_test_51Q9OSlAkr5cb74dk2nUR3unGgdgvdb7NKpPdhqM4weo72i4YSSQ2JFX8YAmRRP20lW2UdH0tsjPCgRDPDkFQiSFK00Wmi8qN26
  stripe-webhook-secret: whsec_XSeFWOS8qaQmZhqmBZfy8LcPje42cvlJ
  jwt-secret: jwt_secret_key
