apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-uri: bW9uZ29kYitzcnY6Ly95M3MycHJvamVjdGdyb3VwOkp1UVQ2eXFuVmRaNkZROTdAZm9vZGZsaXguajBwMHAubW9uZ29kYi5uZXQv
  jwt-secret: and0X3NlY3JldF9rZXk=