apiVersion: v1
kind: Secret
metadata:
  name: delivery-secrets
type: Opaque
stringData:
  MONGO_URI: mongodb+srv://y3s2projectgroup:JuQT6yqnVdZ6FQ97@foodflix.j0p0p.mongodb.net/foodflix-delivery?retryWrites=true&w=majority
  JWT_SECRET: jwt_secret_key
